# Generated by Django 4.2.4 on 2023-09-06 17:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_remove_mode_arms_choice'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=700, null=True)),
                ('arms_choice', models.CharField(choices=[('ARMED', 'Armed'), ('UNARMED(BUT IN POSSESION OF OTHER PROTECTIVE EQUIPMENT)', 'Unarmed(But in Possesion of other protective equipment)')], default='UNARMED(BUT IN POSSESION OF OTHER PROTECTIVE EQUIPMENT)', max_length=70)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.mode')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.tier')),
            ],
        ),
    ]
