# Generated by Django 4.2.4 on 2023-09-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='location',
            field=models.TextField(max_length=700, null=True),
        ),
    ]
