# Generated by Django 4.2.4 on 2023-09-05 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_level', models.CharField(max_length=20, null=True)),
                ('number_of_organizations', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_name', models.CharField(max_length=20, null=True)),
                ('bio', models.CharField(max_length=20, null=True)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.tier')),
            ],
        ),
    ]
