# Generated by Django 4.2.4 on 2023-09-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mode',
            name='arms_choice',
            field=models.CharField(choices=[('ARMED', 'Armed'), ('UNARMED(BUT IN POSSESION OF OTHER PROTECTIVE EQUIPMENT)', 'Unarmed(But in Possesion of other protective equipment)')], default='UNARMED(BUT IN POSSESION OF OTHER PROTECTIVE EQUIPMENT)', max_length=70),
        ),
        migrations.AlterField(
            model_name='mode',
            name='bio',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
