# Generated by Django 4.2.4 on 2023-09-06 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_mode_arms_choice_alter_mode_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mode',
            name='arms_choice',
        ),
    ]
