# Generated by Django 4.2.4 on 2023-09-27 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_remove_mode_arms_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mode',
            name='tier',
        ),
        migrations.AddField(
            model_name='tier',
            name='mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.mode'),
        ),
    ]
