# Generated by Django 4.2.4 on 2023-09-27 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_remove_tier_number_of_organizations_tier_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tier',
            name='mode',
        ),
    ]
