# Generated by Django 4.2.4 on 2023-09-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_remove_tier_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mode',
            name='bio',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
