# Generated by Django 4.2.4 on 2023-09-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_mode_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='mode',
            name='tier',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
